//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Windows;

    public partial class AtelierBaseEntities : DbContext
    {
        private static AtelierBaseEntities _context;

        public AtelierBaseEntities()
            : base("name=AtelierBaseEntities")
        {
        }
        private static bool CheckConnecting()
        {
            try
            {
                AtelierBaseEntities atelie = new AtelierBaseEntities();
                atelie.Database.Connection.Open();
                return true;
            }
            catch
            {
                MessageBox.Show("Отсутствует подключение к серверу.Проверьте подключение и повторите попытку позже!",
                    "Ошибка подключения", MessageBoxButton.OK, MessageBoxImage.Information);
                return false;
            }
        }
        public static AtelierBaseEntities GetContext()
        {
            if (!CheckConnecting())
            {
                Environment.Exit(0);
            }
            if (_context == null)
            {
                _context = new AtelierBaseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Textile> Textile { get; set; }
        public virtual DbSet<TypeOfWorker> TypeOfWorker { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
