//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Windows;

    public partial class AtelierEntities : DbContext
    {
        private static AtelierEntities _context;
        public AtelierEntities()
            : base("name=AtelierEntities")
        {
        }

        private static bool CheckConnection()
        {
            try
            {
                AtelierEntities db = new AtelierEntities();
                db.Database.Connection.Open();
                return true;
            }
            catch
            {
                MessageBox.Show("Отсутствует подключение к серверу. Проверьте подключение и повторите попытку позже", "Ошибка подключения", MessageBoxButton.OK, MessageBoxImage.Information);
                return false;
            }
        }
        public static AtelierEntities GetContext()
        {
            if (!CheckConnection())
            {
                Environment.Exit(0);
            }
            if (_context == null)
                _context = new AtelierEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Textile> Textile { get; set; }
        public virtual DbSet<TypeOfWorker> TypeOfWorker { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
