//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdWorker { get; set; }
        public int IdService { get; set; }
        public int IdTextile { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public decimal Price { get; set; }
        public bool IsCompleted { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual Textile Textile { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
